/**
 * Created by Obscurity on 2017/1/22.
 */

$("#container").hshare({
    size: "large",
    copyLink: true,
    print: true,
    bookmark: true,
    platforms: [{
        name: "kaixin"
    }, {
        name: "pengyou"
    }, {
        name: "qzone"
    }, {
        name: "tieba"
    }, {
        name: "douban"
    }, {
        name: "qq"
    }, {
        name: "renren"
    }, {
        name: "sinaweibo"
    }, {
        name: "wechat"
    }, {
        name: "renminweibo"
    }, {
        name: "hexunweibo"
    }, {
        name: "tianya"
    }, {
        name: "reddit"
    }, {
        name: "yixin"
    }, {
        name: "club189"
    }, {
        name: "googleplus"
    }, {
        name: "tumblr"
    }, {
        name: "hotmail"
    }, {
        name: "ibaidu"
    }, {
        name: "baiduhome"
    }, {
        name: "linkedin"
    }, {
        name: "twitter"
    }, {
        name: "facebook"
    }, {
        name: "feixin"
    }, {
        name: "youdaocloud"
    }, {
        name: "qingbiji"
    }, {
        name: "sdonote"
    }, {
        name: "xinhua"
    }, {
        name: "isohu"
    }, {
        name: "gmail"
    }, {
        name: "instapaper"
    }, {
        name: "netvibes"
    }, {
        name: "pocket"
    }]
});

$("#container2").hshare({
    size: "medium",
    copyLink: true,
    print: true,
    bookmark: true,
    platforms: [{
        name: "kaixin"
    }, {
        name: "pengyou"
    }, {
        name: "qzone"
    }, {
        name: "tieba"
    }, {
        name: "douban"
    }, {
        name: "qq"
    }, {
        name: "renren"
    }, {
        name: "sinaweibo"
    }, {
        name: "wechat"
    }, {
        name: "renminweibo"
    }, {
        name: "hexunweibo"
    }, {
        name: "tianya"
    }, {
        name: "reddit"
    }, {
        name: "yixin"
    }, {
        name: "club189"
    }, {
        name: "googleplus"
    }, {
        name: "tumblr"
    }, {
        name: "hotmail"
    }, {
        name: "ibaidu"
    }, {
        name: "baiduhome"
    }, {
        name: "linkedin"
    }, {
        name: "twitter"
    }, {
        name: "facebook"
    }, {
        name: "feixin"
    }, {
        name: "youdaocloud"
    }, {
        name: "qingbiji"
    }, {
        name: "sdonote"
    }, {
        name: "xinhua"
    }, {
        name: "isohu"
    }, {
        name: "gmail"
    }, {
        name: "instapaper"
    }, {
        name: "netvibes"
    }, {
        name: "pocket"
    }]
});

$("#container3").hshare({
    size: "small",
    copyLink: true,
    print: true,
    bookmark: true,
    platforms: [{
        name: "kaixin"
    }, {
        name: "pengyou"
    }, {
        name: "qzone"
    }, {
        name: "tieba"
    }, {
        name: "douban"
    }, {
        name: "qq"
    }, {
        name: "renren"
    }, {
        name: "sinaweibo"
    }, {
        name: "wechat"
    }, {
        name: "renminweibo"
    }, {
        name: "hexunweibo"
    }, {
        name: "tianya"
    }, {
        name: "reddit"
    }, {
        name: "yixin"
    }, {
        name: "club189"
    }, {
        name: "googleplus"
    }, {
        name: "tumblr"
    }, {
        name: "hotmail"
    }, {
        name: "ibaidu"
    }, {
        name: "baiduhome"
    }, {
        name: "linkedin"
    }, {
        name: "twitter"
    }, {
        name: "facebook"
    }, {
        name: "feixin"
    }, {
        name: "youdaocloud"
    }, {
        name: "qingbiji"
    }, {
        name: "sdonote"
    }, {
        name: "xinhua"
    }, {
        name: "isohu"
    }, {
        name: "gmail"
    }, {
        name: "instapaper"
    }, {
        name: "netvibes"
    }, {
        name: "pocket"
    }]
});